CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    role       VARCHAR(255) NOT NULL
);

CREATE TABLE profiles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    user_id    BIGINT    NOT NULL UNIQUE,
    bio        TEXT,
    avatar_url VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE tags
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    name       VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    name       VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    category_id BIGINT,
    teacher_id  BIGINT,
    FOREIGN KEY (category_id) REFERENCES categories (id),
    FOREIGN KEY (teacher_id) REFERENCES users (id)
);

CREATE TABLE course_tags
(
    course_id BIGINT NOT NULL,
    tag_id    BIGINT NOT NULL,
    PRIMARY KEY (course_id, tag_id),
    FOREIGN KEY (course_id) REFERENCES courses (id),
    FOREIGN KEY (tag_id) REFERENCES tags (id)
);

CREATE TABLE course_reviews
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    course_id         BIGINT    NOT NULL,
    student_id        BIGINT    NOT NULL,
    rating            INT       NOT NULL,
    comment           TEXT,
    created_at_review TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses (id),
    FOREIGN KEY (student_id) REFERENCES users (id)
);

CREATE TABLE course_schedules
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    course_id  BIGINT    NOT NULL,
    start_date DATE,
    end_date   DATE,
    weekday    VARCHAR(255),
    FOREIGN KEY (course_id) REFERENCES courses (id)
);

CREATE TABLE modules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    course_id   BIGINT       NOT NULL,
    title       VARCHAR(255) NOT NULL,
    order_index INT,
    FOREIGN KEY (course_id) REFERENCES courses (id)
);

CREATE TABLE lessons
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    module_id  BIGINT       NOT NULL,
    title      VARCHAR(255) NOT NULL,
    content    TEXT,
    video_url  VARCHAR(255),
    FOREIGN KEY (module_id) REFERENCES modules (id)
);

CREATE TABLE materials
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    lesson_id   BIGINT       NOT NULL,
    type        VARCHAR(255),
    title       VARCHAR(255) NOT NULL,
    url         VARCHAR(255),
    description TEXT,
    FOREIGN KEY (lesson_id) REFERENCES lessons (id)
);

CREATE TABLE assignments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    lesson_id   BIGINT       NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    due_date    TIMESTAMP,
    max_score   INT DEFAULT 100,
    FOREIGN KEY (lesson_id) REFERENCES lessons (id)
);

CREATE TABLE quizzes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    module_id  BIGINT UNIQUE,
    title      VARCHAR(255),
    FOREIGN KEY (module_id) REFERENCES modules (id)
);

CREATE TABLE submissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL,
    assignment_id BIGINT    NOT NULL,
    student_id    BIGINT    NOT NULL,
    submitted_at  TIMESTAMP,
    content       TEXT,
    score         INT,
    feedback      TEXT,
    UNIQUE (assignment_id, student_id),
    FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    FOREIGN KEY (student_id) REFERENCES users (id)
);

CREATE TABLE quiz_submissions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    quiz_id    BIGINT    NOT NULL,
    student_id BIGINT    NOT NULL,
    score      INT,
    taken_at   TIMESTAMP,
    FOREIGN KEY (quiz_id) REFERENCES quizzes (id),
    FOREIGN KEY (student_id) REFERENCES users (id)
);

CREATE TABLE questions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    quiz_id    BIGINT       NOT NULL,
    text       TEXT         NOT NULL,
    type       VARCHAR(255) NOT NULL,
    FOREIGN KEY (quiz_id) REFERENCES quizzes (id)
);

CREATE TABLE answer_options
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    question_id BIGINT    NOT NULL,
    text        TEXT      NOT NULL,
    is_correct  BOOLEAN   NOT NULL,
    FOREIGN KEY (question_id) REFERENCES questions (id)
);

CREATE TABLE enrollments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    student_id BIGINT       NOT NULL,
    course_id  BIGINT       NOT NULL,
    enrol_date TIMESTAMP,
    status     VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    UNIQUE (student_id, course_id),
    FOREIGN KEY (student_id) REFERENCES users (id),
    FOREIGN KEY (course_id) REFERENCES courses (id)
);

CREATE TABLE notifications
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    user_id         BIGINT    NOT NULL,
    message         TEXT      NOT NULL,
    read            BOOLEAN DEFAULT FALSE,
    created_at_note TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id)
);